apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: multiapp-onecluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kanuahs/argocd-demo.git'
    path: app-of-apps-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true