apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-apps-envs-appset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: FOSCOLL
    environment: QA
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/byreshkumar/argoproject.git'
    targetRevision: main
    helm:
      valueFiles:
      - values_qa_foscoll_commons.yaml
  sources: []
  project: default
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
    - PruneLast=true
    - PrunePropagationPolicy=background
